version: "3"
services:
  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    networks:
      - traefik
    ports:
      - "2222:2222"
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_LISTEN_PORT=2222
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=registry"
networks:
  traefik:
    external: true
