global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: dns-cloudflare
        domains:
          - main: "change_domain"
            sans:
              - "*.change_domain"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    swarmMode: false
  file:
    filename: /dynamic.yml
    watch: true

certificatesResolvers:
  dns-cloudflare:
    acme:
      email: change_mail
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
