version: "3"
services:
  rwtxt:
    image: docker.io/schollz/rwtxt:latest
    container_name: rwtxt
    networks:
      - traefik
    volumes:
      - ./data:/data
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=registry"
networks:
  traefik:
    external: true
